baseURL: "https://uhyogo-epa.github.io"
theme: "up-business-theme-rev"
languageCode: "ja"

title: "電力応用工学G"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "uh-epa"
  description: "Electric Power Applications Laboratory in University of Hyogo."
  images: 
    - "images/hero-image.png"

  logo: "logo-uh.gif"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "兵庫県姫路市書写2167"

  contact:
    - "h930h019+@+guh.u-hyogo.ac.jp"

  copyright: "© 2024 · Powered by Hugo & Up Business"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "ニュース"
      url: "/news"
      weight: 3


    - name: "メンバー"
      url: "/members"
      weight: 3

    - name: "研究成果"
      url: "/publications"
      weight: 4


  # buttons:
  #   - name: "Book a call"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "メンバー"
      url: "/members"
      weight: 3

    - name: "研究成果"
      url: "/publications"
      weight: 4


taxonomies:
  series: "series"
  tags: "tags"
